apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpsink
  namespace: tssc-gitops
  labels:
    app.kubernetes.io/name: httpsink
    backstage.io/app: httpsink
spec:
  project: default
  source:
    repoURL: https://github.com/redhat-ads-tech/m2-argocd-example
    targetRevision: HEAD
    path: k8s
  destination:
    name: in-cluster
    namespace: httpsink
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
