openapi: 3.0.0
info:
  title: Balance Check API
  version: 1.0.0
  description: API for real-time account balance inquiries and balance history
servers:
  - url: https://api.example.com/balances
    description: Production server
paths:
  /accounts/{accountId}/balance:
    get:
      summary: Get current balance
      description: Retrieve the current balance for a specific account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Current balance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
  /accounts/{accountId}/balance-history:
    get:
      summary: Get balance history
      description: Retrieve balance history for a specific account
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Balance history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BalanceHistory'
components:
  schemas:
    Balance:
      type: object
      properties:
        accountId:
          type: string
        currentBalance:
          type: number
        availableBalance:
          type: number
        currency:
          type: string
        lastUpdated:
          type: string
          format: date-time
    BalanceHistory:
      type: object
      properties:
        date:
          type: string
          format: date
        balance:
          type: number
        currency:
          type: string 