openapi: 3.0.0
info:
  title: Standing Orders API
  version: 1.0.0
  description: API for managing recurring payments and standing orders
servers:
  - url: https://api.example.com/standing-orders
    description: Production server
paths:
  /standing-orders:
    post:
      summary: Create standing order
      description: Create a new standing order for recurring payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StandingOrder'
      responses:
        '201':
          description: Standing order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandingOrder'
    get:
      summary: List standing orders
      description: Retrieve all standing orders for an account
      parameters:
        - name: accountId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of standing orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StandingOrder'
  /standing-orders/{standingOrderId}:
    get:
      summary: Get standing order
      description: Retrieve details of a specific standing order
      parameters:
        - name: standingOrderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Standing order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StandingOrder'
    delete:
      summary: Cancel standing order
      description: Cancel an existing standing order
      parameters:
        - name: standingOrderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Standing order cancelled
components:
  schemas:
    StandingOrder:
      type: object
      properties:
        id:
          type: string
        accountId:
          type: string
        beneficiaryId:
          type: string
        amount:
          type: number
        currency:
          type: string
        frequency:
          type: string
          enum: [weekly, monthly, quarterly, annually]
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        status:
          type: string
          enum: [active, cancelled, completed]
        lastPaymentDate:
          type: string
          format: date
        nextPaymentDate:
          type: string
          format: date 