openapi: 3.0.0
info:
  title: Transaction History API
  version: 1.0.0
  description: API for retrieving and filtering customer transaction history and statements
servers:
  - url: https://api.example.com/transactions
    description: Production server
paths:
  /accounts/{accountId}/transactions:
    get:
      summary: Get account transactions
      description: Retrieve transactions for a specific account with optional filtering
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: fromDate
          in: query
          schema:
            type: string
            format: date
        - name: toDate
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
  /accounts/{accountId}/statements:
    get:
      summary: Get account statements
      description: Retrieve account statements for a specific period
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: year
          in: query
          required: true
          schema:
            type: integer
        - name: month
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Account statement
          content:
            application/pdf:
              schema:
                type: string
                format: binary
components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date-time
        amount:
          type: number
        currency:
          type: string
        type:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [pending, completed, failed] 