apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payment-initiation-api
  description: API to initiate payments from customer accounts
  tags:
    - pis
    - payments
spec:
  type: openapi
  lifecycle: production
  owner: payments-team
  definition:
    $text: https://github.com/rhdh-demo-gh/ob-demo/blob/main/specs/payments.spec.yaml