apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: transaction-history-api
  description: API for retrieving and filtering customer transaction history and statements
spec:
  type: openapi
  lifecycle: production
  owner: accounts-team
  definition:
    $text: https://github.com/rhdh-demo-gh/ob-demo/blob/main/specs/transactions.spec.yaml 